# Riverpod 程式碼生成配置
# 這個檔案告訴 build_runner 如何生成 Riverpod provider

targets:
  $default:
    builders:
      # Riverpod Generator 設定
      riverpod_generator:riverpod_generator:
        options:
          # 生成的程式碼使用 Riverpod 3.0 的新語法
          riverpod_version: 3

      # 自定義 Lint 設定
      riverpod_lint:custom_lint_builder:
        enabled: true
